canonical/sdcore-amf-k8s-operator

lib/charms/sdcore_nrf/v0/fiveg_nrf.py
Fetches the latest version of the `fiveg_nrf` lib
=> Fetches the latest version of fiveg_nrf lib

.github/workflows/main.yaml
Runs the CI on a schedule each week to build and publish the charm.
The CI will run each Tuesday 10 AM UTC.
=> Runs the CI on a schedule each week to build and publish the charm

.github/workflows/main.yaml
Uses the workflow file from `sdcore-github-workflows` repo.
=> Fixes check libraries workflow

.github/workflows/main.yaml
Changes the schedule time to Sunday 6 AM UTC. 
Just to be synced with the rest of the sdcore charms.
=> Changes schedule time to Sunday 6 AM

renovate.json
Modifies the configuration of renovate to scan dependencies in the tox.ini file
=> Modifies the configuration of renovate to scan dependencies in tox.ini

README.md, metadata.yaml, src/charm.py, tests/unit/test_charm.py
- Updates integrations in the `README.md`
- Updates NRF relation name to match the `README` (and convention we use in all other charms)
=> (FIX) Fixing inconsistencies between the README and the implementation

metadata.yaml
Updates the charm metadata to include website, source, and issues URLs.
=> Update charm metadata

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/observability_libs/v0/juju_topology.py, lib/charms/observability_libs/v1/kubernetes_service_patch.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, requirements.txt
Side effect: removes a deprecation warning.
=> Update charm libs

src/charm.py
Prevent scaling by blocking on non-leader units.
Add note about best-effort removal of the k8s service.
=> fix: Prevent scaling by blocking on non-leader units

README.md, tests/integration/test_integration.py
Bumps MongoDB operator version. A similar PR will be made in all of the 5G NF's and bundle that leverage MongoDB.
=> feat: Bumps MongoDB operator version

tests/unit/test_charm.py
This PR aims to replace mock objects for `ops.model.Container.exec`, leveraging the new `ops.harness.handle_exec` method.
=> chore: Reduce amount of mocking

README.md
Reverts canonical/sdcore-amf-k8s-operator#60
=> chore: Revert "Dummy PR to publish charm after changing name"

README.md, tests/integration/test_integration.py
Uses stable release of self-signed certificates
=> chore: Uses stable release of self-signed certificates

src/charm.py
- Refactoring the `def on_collect_unit_status` and  `def _configure_amf` methods to increase readability.
- Adding unit leader check in charm constructor.
=> chore: Improve status management

.github/workflows/main.yaml, .github/workflows/promote.yaml
Updates the track to `1.5` which will be the next release
=> chore: Updating the track for next release

terraform/variables.tf, tests/integration/test_integration.py
=> chore: Refactoring integration tests

.github/workflows/codeql-analysis.yml, .github/workflows/dependabot_pr.yaml, .github/workflows/issues.yaml, .github/workflows/main.yaml, .github/workflows/promote.yaml, tests/integration/conftest.py, tests/integration/test_integration.py
Build charm in independent workflow step using the new `v1.0.0` release of sdcore-github-workflows.
=> chore: build charm in independent workflow step

CONTRIBUTING.md, tests/integration/test_integration.py
Updating CONTRIBUTING.md with the note about integration tests requiring charm to be built
=> chore: Updating CONTRIBUTING.md

.github/dependabot.yml, .github/workflows/1_4_scheduled_runs.yaml
Configures scheduled runs for `v1.4`
=> chore: Configuring scheduled runs for v1.4

terraform/terraform.tf
=> chore: Update tf version to 0.12.0

.github/workflows/main.yaml
Always use current ref as a source
=> fix: Use current branch as a source

.github/workflows/1_4_scheduled_runs.yaml
Allow running 1.4 scheduled runs manually for tests
=> chore: Allow running 1.4 scheduled runs manually for tests

.github/workflows/1_4_scheduled_runs.yaml
Removing manual trigger for 1.4 scheduled runs
=> chore: Removing manual trigger for 1.4 scheduled runs

tests/integration/test_integration.py
Adds relation between NRF and Webui
=> chore: Adds relation between NRF and Webui

README.md, charmcraft.yaml
=> chore: Bump AMF to 1.4.2

README.md
Fixes channels in the `README`.
Original commands would result in deploying a mix of `1.4` and `1.5`.
=> fix: Fixes channels in the README

src/charm.py
Remove now unnecessary csr variable
=> chore: remove now unused csr variable

requirements.txt, test-requirements.txt, tests/unit/expected_config/config.conf, tests/unit/lib/charms/sdcore_amf/v0/test_fiveg_n2_provider_interface.py, tests/unit/lib/charms/sdcore_amf/v0/test_fiveg_n2_requirer_interface.py, tests/unit/test_charm_certificates_relation_broken.py, tests/unit/test_charm_collect_status.py, tests/unit/test_charm_configure.py, tests/unit/test_charm_fiveg_n2_relation_joined.py, tests/unit/test_charm_remove.py
Updates Scenario to version 7.0, and makes the corresponding adjustments to the tests.
=> chore: update to Scenario 7

CONTRIBUTING.md
=> chore: bump microk8s to v1.31

.github/workflows/main.yaml
Removes scheduled runs of the CI
=> chore: Removes scheduled runs of the CI

.github/workflows/1_5_scheduled_runs.yaml
Adds scheduled CI runs for `v1.5` release
=> chore: Adds scheduled CI runs for v1.5 release

src/charm.py
Fixes lint report issue blocking renovate PRs from being merged
=> fix: Fixes lint report
