canonical/sdcore-amf-k8s-operator

- src/charm.py
- src/templates/amfcfg.conf.j2
- tests/unit/expected_config/config.conf
Uses pod IP instead of URL for registerIPv4 config
> Using IP instead of URL for registerIPv4 config

- metadata.yaml
- src/charm.py
- src/templates/amfcfg.conf.j2
- tests/integration/test_integration.py
- tests/unit/expected_config/config.conf
- tests/unit/test_charm.py
- Removes the default database that was never used in the charm
- Uses the URL from the "sdcore_amf" database to enter into the amf configuration file
> [Bug fix] AMF only relies on 1 database "sdcore_amf"

- src/charm.py
AMF metrics weren't forwarded to Grafana Agent and prometheus. This PR adds a job to metrics endpoint provider to do exactly that.
> [Bug fix] Adds job to metrics endpoint provider

- README.md
- charmcraft.yaml
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- metadata.yaml
- requirements.txt
- src/charm.py
- src/templates/amfcfg.conf.j2
- tests/integration/test_integration.py
- tests/unit/test_charm.py
Implements certificates interface and new certificate management. Here the AMF will be set to use HTTPS for its SBI interface only when certificates are available (the relation to the TLS provider was created and certificates were provided).
Event management:
- On certificates relation created: Creates private key
- On certificates relation joined: Creates CSR based on private key and requests certificate
- On certificate available: Stores certificate and reconfigures the AMF workload to use HTTPS instead of HTTP
- On certificates relation broken: Deletes private key, CSR and Certificate and reconfigurs AMF workload to use HTTP instead of HTTPS
Notes:
- The path for certificates are hardcoded in the AMF code (ref [here](https://github.com/omec-project/amf/blob/master/util/path.go#L17))
> [Feat] Implements certificates interface

- requirements.txt
Pins `ops` version to 2.4.1, which is currently the last one compatible with `scenario`. Newer versions are causing integration and units tests failures.
> (FIX) Downgrading ops to 2.4.1

- lib/charms/sdcore_nrf/v0/fiveg_nrf.py
- src/charm.py
- test-requirements.txt
- tests/integration/test_integration.py
- tests/unit/test_charm.py
This PR adds handling of the NRF relation broken event. 
If NRF will ever go down, the AMF charm will reflect that fact by going into `Blocked` state.
> (TELCO-574) block charm when NRF goes down

- README.md
- config.yaml
- src/charm.py
- tests/unit/test_charm.py
Expose the `NGAPP` port as a LoadBalancer Service to enable external access from edge RAN. Also add IP and hostname configuration items to allow the administrator to override the defaults for specific network configurations.
> Expose NGAPP port as a Loadbalancer Service

- tests/integration/test_integration.py
`add_relation()` is deprecated and will be removed in the future. This removes the warning log.
Also, assert assumptions instead of ignoring the type checker.
> Use integrate() instead of add_relation()

- src/charm.py
- tests/unit/test_charm.py
In case something happens to cause our charm to go down without properly cleaning up the service, use `client.apply()` instead of client.create()`.
`apply()` will ensure the service configuration matches what is expected, but is OK if it already exists, unlike `create()` which will throw an error if the service already exists.
This will also prevent errors when scaling up (even though scaling isn't supported at this time).
> fix: Protect against load balancer service already existing

- README.md
- tests/integration/test_integration.py
Reverts because this bug has been observed: https://github.com/canonical/mongodb-k8s-operator/issues/212
> revert: "feat: Bumps MongoDB operator version"

- src/charm.py
- tests/unit/test_charm.py
This PR aims to fix #45. The fix catches the `TypeError` exception thrown when trying to access ingress information when MetalLB is not enabled or properly configured, and leverages the validation from the N2 interface to set the charm into blocked status.
> fix: go into blocked status if MetalLB is not enabled and N2 relation is set

- src/charm.py
- tests/unit/test_charm.py
This PR replaces `KubernetesServicePatch` with `ops.set_ports` for setting the ports exposed by the workload.
It's worth noting, that with ops.set_ports we're not able to set custom name for the port. ops will automatically set the name of the port to `juju-{PORT_NUMBER}-tcp`.
> chore: Replacing KubernetesServicePatch with ops.set_ports

- .github/workflows/main.yaml
- README.md
- lib/charms/sdcore_amf_k8s/v0/fiveg_n2.py
- lib/charms/sdcore_nrf_k8s/v0/fiveg_nrf.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- test-requirements.txt
- tests/integration/test_integration.py
- tests/unit/lib/charms/sdcore_amf/v0/test_fiveg_n2_provider_interface.py
- tests/unit/lib/charms/sdcore_amf/v0/test_fiveg_n2_requirer_interface.py
- tests/unit/test_charm.py
- tox.ini
Add -k8s as a suffix in both github and Charmhub name to follow [TE042](https://docs.google.com/document/d/1R0UzoPr3vvorhbBJYBz-5gZkTCTL2a9_R6xV8K4_i-8/edit).
- Create new fiveg_n2 library
- Pin macaroonbakery to 1.3.2 which installed by juju client indirectly through pytest_operator.
- The next protobuf version 4.21.0 has the breaking changes with the existing code
- https://protobuf.dev/news/2022-05-06/#python-updates
> chore: Rename SD-Core charms by adding -k8s as a suffix

- README.md
- lib/charms/sdcore_nrf_k8s/v0/fiveg_nrf.py
- metadata.yaml
- src/charm.py
- terraform/outputs.tf
- tests/unit/test_charm.py
NRF and AMF use different relation names for fiveg_nrf interface. All the other charms uses fiveg_nrf. We need to use the same naming convention in all charms. For this reason interface name is changed from fiveg-nrf -> fiveg_nrf within this PR.
> chore: Change interface name from fiveg-nrf to fiveg_nrf

- charmcraft.yaml
Use `build-packages` instead of pre-built binaries. This addresses a bug that we currently have building the charm:
```
Building wheel for cffi (pyproject.toml): finished with status 'error'
::    ::   error: subprocess-exited-with-error
::    ::
::    ::   × Building wheel for cffi (pyproject.toml) did not run successfully.
::    ::   │ exit code: 1
::    ::   ╰─> [39 lines of output]
::    ::       running bdist_wheel
::    ::       running build
::    ::       running build_py
::    ::       creating build
::    ::       creating build/lib.linux-x86_64-cpython-310
::    ::       creating build/lib.linux-x86_64-cpython-310/cffi
::    ::       copying src/cffi/setuptools_ext.py -> build/lib.linux-x86_64-cpython-310/cffi
::    ::       copying src/cffi/verifier.py -> …
```
> chore: build python packages during build

- src/charm.py
- tests/unit/test_charm.py
The global constant called DEFAULT_FIELD_MANAGER is set to a default value which is `controller` refers the name of Juju controller that is not always correct.  Replacing  DEFAULT_FIELD_MANAGER with the charm name as it is the charm in charge of managing the field.
> fix: Using charm name as DEFAULT_FIELD_MANAGER

- lib/charms/sdcore_amf_k8s/v0/fiveg_n2.py
- pyproject.toml
- src/charm.py
- test-requirements.in
- test-requirements.txt
- tests/unit/test_charm.py
- tox.ini
Move to ruff and codespell for linting. `pyproject-flake8` is currently broken on Python 3.12, making development on Noble break.
> chore: Move to codespell and ruff 

- src/charm.py
The Collect unit status is being observed twice in the charm constructor. This PR eliminates the duplicated event observation.
> chore: Remove duplicated collect-status observation

- .github/workflows/1_4_scheduled_runs.yaml
Trying to use branch name instead of release to specify the shared workflows version, to stop Dependabot from updating it
> fix: Using branch name instead of release for shared workflows

- tests/unit/test_charm.py
This PR aims to remove `unittest` framework in favor of `pytest`, as described [here](https://juju.is/docs/sdk/write-a-unit-test-for-a-charm).
Main changes:
* Use fixtures to configure harness and patches
* Use fixtures to create `database`, `fiveg_nrf`, `certificates` relations
> chore: use pytest for unit tests

- README.md
- charmcraft.yaml
- lib/charms/sdcore_webui_k8s/v0/sdcore_config.py
- src/charm.py
- src/templates/amfcfg.conf.j2
- tests/integration/test_integration.py
- tests/unit/expected_config/config.conf
- tests/unit/test_charm.py
- Implement the requirer side of sdcore-config interface.
- Place main callback method `def _configure_amf` just after Charm constructor.
> feat: Implement the requirer side of `sdcore-config` interface

- charmcraft.yaml
- src/charm.py
- tests/unit/test_charm.py
Checks the running container for a specific /etc/workload-version file. If it exists, the content of that file is reported in the app version field.
> feat: adding workload version

- src/charm.py
- src/k8s_service.py
- tests/unit/test_charm.py
The AMF has k8s specific code used to create/remove the NGAP service. It used to be entangled in the charm class. Here , we move this k8s specific code to its own class and file. This separates concerns and move the dependencies closer to their actual use. This also allows for simplifying unit tests.
Here we did not write unit tests for this new class as it is a thin layer with close to 0 logic.
> chore: move k8s specific code to its own class

- src/k8s_service.py
- tests/unit/test_charm.py
There was an error introduced in one of my prior PR's that caused errors when getting the AMF external IP address (PR #345). Here we now catch  the lightkube APIError when fetching external service. 
```
unit-sdcore-amf-k8s-0: 12:35:35 ERROR unit.sdcore-amf-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-sdcore-amf-k8s-0/charm/venv/lightkube/core/generic_client.py", line 188, in raise_for_status
resp.raise_for_status()
File "/var/lib/juju/agents/unit-sdcore-amf-k8s-0/charm/venv/httpx/_models.py", line 761, in raise_for_status
raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://10.152.183.1/api/v1/namespaces/test-integration-9doe/services/ …
```
> fix: catch API error when fetching external service

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- tests/unit/certificates_helpers.py
Certificate helpers have been added to the tls certificates library v4. Here we leverage those helpers and get rid of local implementations.
> test: leverage certificate helpers

- src/charm.py
- tests/unit/certificates_helpers.py
- tests/unit/test_charm_configure.py
Here we had a unit test that was not going into the expected code path. We were never going to the point of comparing the existing cert to the new one.
> test: fix unit test that was not asserting that certificates were not updated unnecessarily

- test-requirements.in
- test-requirements.txt
- tests/unit/fixtures.py
- tests/unit/lib/charms/sdcore_amf/v0/test_fiveg_n2_provider_interface.py
- tests/unit/lib/charms/sdcore_amf/v0/test_fiveg_n2_requirer_interface.py
- tests/unit/test_charm_certificates_relation_broken.py
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
- tests/unit/test_charm_fiveg_n2_relation_joined.py
- tests/unit/test_charm_remove.py
Now that scenario testing is built into ops we don't need to import it as a separate dependency. Here we use `ops.testing` instead of scenario. Both have the same API.
> chore: use built-in testing from ops

- src/charm.py
`ops.main.main()` is deprecated. Here, we replace it with `ops.main()`.
```
/var/lib/juju/agents/unit-gnbsim-0/charm/./src/charm.py:510: DeprecationWarning: Calling ops.main.main() is deprecated, call ops.main() instead
main(GNBSIMOperatorCharm)
```
> chore: replace `ops.main.main()` with `ops.main`

- src/prometheus_alert_rules/amf_down.rule
This PR aims to add the alert rule for AMF availability. The alert will be fired when AMF remains down for at least 5 minutes.
> feat: add alert rule for AMF availability

- charmcraft.yaml
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- lib/charms/tempo_coordinator_k8s/v0/tracing.py
- requirements.in
- requirements.txt
- src/charm.py
- test-requirements.txt
- tests/integration/test_integration.py
Add charm tracing support using the Observability team's `tracing` charm relation interface.
Charm tracing allows developers to vizualize code paths traversed during charm events and to know the amount of time spent in each function. This is useful for both troubleshooting and performance engineering.
1. Deploy cos-lite and tempo
2. Deploy AMF K8s
3. Integrate AMF k8s with tempo
> feat: add charm tracing support

- .github/renovate.json5
Use semantic commits in Renovate.
> fix: Use semantic commits in Renovate

- .github/renovate.json5
- Configures renovate to cover `v1.5` release branch
- Excludes `pytest-asyncio` from renovate updates
Reference:
https://docs.renovatebot.com/configuration-options/#matchbasebranches
> chore: Configures renovate to cover v1.5 release branch

- charmcraft.yaml
- src/charm.py
- src/templates/amfcfg.conf.j2
- tests/unit/expected_config/config.conf
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
- tests/unit/test_charm_fiveg_n2_relation_joined.py
Here we add a `log-level` configuration option with a reasonable default value (`info`). The allowed options are the same as in the AMF workload: `debug`, `info`, `warn`, `error`, `fatal`, `panic`.
In most deployments, the log level should be set to `info` to ensure the log quantity is reasonable. 
```
2024-12-05T14:21:38.034Z [pebble] Service "amf" starting: /bin/amf --amfcfg /free5gc/config/amfcfg.conf
2024-12-05T14:21:38.044Z [amf] 2024-12-05T14:21:38.044Z	INFO	build/amf.go:24	amf	{"component": "AMF", "category": "App"}
2024-12-05T14:21:38.045Z [amf] 2024-12-05T14:21:38.045Z	INFO	service/init.go:239	AMF Log level is set to [info] level	{"component": "AMF", "category": "Init"}
2024-12-05T14:21:38.045Z [amf] 2024-12-05T14:21:38.045Z	INFO	logger/logger.go:103	set log level: info …
```
> feat: add log-level configuration option

- charmcraft.yaml
- src/charm.py
- src/templates/amfcfg.conf.j2
- tests/unit/expected_config/config.conf
- tests/unit/test_charm_configure.py
TLS paths and  the configuration paths are parameterized in the Upstream with AMF version 1.6.0.
To use the Workload 1.6.0 and higher versions, this PR which specifies configuration and TLS file paths is required.
`Warning: A new Rock version (1.6.0 or higher) should be used with this PR. Integration tests fails until we create a new Rock version and start to use it.`
> feat: specify the configuration path to use AMF version 1.6.0

- terraform/main.tf
- terraform/variables.tf
- tests/integration/test_integration.py
By default, Juju fetches charms with base matching the host OS. It means that when running Jammy, Juju won’t use latest charms, because we’ve changed the base to Noble.
Adding an optional (as per CC006) config param base will allow using Noble (base should be set to ubuntu@24.04) regardless of the host OS.
Enforcing Noble on a Juju model configuration level is not an option, because it breaks COS integration (COS charms are not available in ubuntu@24.04).
As a workaround to this issue https://github.com/juju/python-libjuju/issues/1240 we use, series instead of base in the integration tests.
> fix: Uses ubuntu@24.04 in TF module and integration tests

- README.md
- charmcraft.yaml
Bump the underlying workload to the latest upstream release: v1.6.4
- https://github.com/omec-project/amf/releases/tag/v1.6.4
> chore: bump amf rock to v1.6.4

- .github/workflows/1_5_scheduled_runs.yaml
- .github/workflows/issues.yaml
- .github/workflows/main.yaml
- .github/workflows/promote.yaml
- .github/workflows/tics.yaml
- .github/workflows/update-libs.yaml
Adds a TiCS static analysis workflow to run every week, which is the maximum frequency recommend.
The manual trigger option allows developers to manually trigger the analysis workflow whenever needed.
> feat: add TICS static analysis workflow

- tox.ini
Update tox file to produce a `coverage.xml` when unit tests run.This is necessary as TICS static analysis requires a coverage.xml.
> chore: TICS static analysis require coverage.xml

- tests/integration/test_integration.py
Grafana agent charm has been release to  `1/stable`. This PR updates it in the integration tests
> fix: set grafana agent channel to 1/stable in integration tests

- pyproject.toml
- uv.lock
We've released Ops 3.0.0, which identical to Ops 2.23.0 except lower bound on Python was bumped to 3.10.
Since this repo has that lower bound for Python already, I figured this is a good candidate to bump Ops to 3.x.
> chore: bump to Ops 3.x
